# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160906_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
