# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='Cookies', max_length=128),
        ),
    ]
