# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160906_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='home/images/uploaded_recipe_images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='num_servings',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ready_in',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
