# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cook_time',
            new_name='cook_time_hours',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='prep_time',
            new_name='cook_time_minutes',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ready_in',
            new_name='prep_time_hours',
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ready_in_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ready_in_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
