# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20160912_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientline',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='IngredientLine',
        ),
    ]
