# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 21:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20160914_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
