# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_recipe_user_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproxy',
            name='session',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
